# Generated by Django 4.2.5 on 2023-09-13 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketName', models.CharField(max_length=100, verbose_name='Name of the Market')),
                ('city', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100, verbose_name='Adress')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observation')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prices.base')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.market')),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
            bases=('prices.base',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prices.base')),
                ('productName', models.CharField(max_length=100, verbose_name='Name of the Product')),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('G', 'Grains'), ('P', 'Meat'), ('S', 'Spices'), ('F', 'Fruits'), ('V', 'Vegatables'), ('H', 'Hygiene'), ('C', 'Cleaning'), ('B', 'Beverages'), ('D', 'Candies')], max_length=1)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observation')),
            ],
            bases=('prices.base',),
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prices.base')),
                ('purchaseDate', models.DateField(blank=True, null=True)),
                ('id_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.price')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.product')),
            ],
            bases=('prices.base',),
        ),
        migrations.AddField(
            model_name='price',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.product'),
        ),
    ]
